<template>
  <section class="page admin-user-page">
    <div class="page-head">
      <div><span class="eyebrow">ADMIN / USER DETAIL</span><h1>{{ detail.user?.username ? `@${detail.user.username}` : '' }}</h1><p>查看账户状态、使用量和充值兑换记录。</p></div>
      <router-link class="secondary-btn" to="/admin">返回用户列表</router-link>
    </div>

    <div v-if="detail.user" class="metric-grid">
      <div class="metric-card highlight"><span>当前余额</span><strong>¥{{ money(detail.user.balance) }}</strong><small>{{ detail.user.enabled ? '账户正常' : '账户已停用' }}</small></div>
      <div v-for="range in ranges" :key="range.key" class="metric-card"><span>{{ range.label }} Token</span><strong>{{ compact(detail.usage?.[range.key]?.total_tokens) }}</strong><small>请求 {{ detail.usage?.[range.key]?.requests || 0 }} 次 / ¥{{ money(detail.usage?.[range.key]?.total_cost) }}</small></div>
    </div>

    <div v-if="detail.user" class="admin-detail-grid">
      <div class="panel"><div class="panel-head"><div><span class="eyebrow">USAGE CHART</span><h2>每日使用趋势</h2></div></div><div class="bar-chart"><div v-for="item in (detail.usage.chart || [])" :key="item.day" class="bar-item"><div class="bar-value" :style="{ height: barHeight(item.tokens) }"><span>{{ compact(item.tokens) }}</span></div><small>{{ item.day.slice(5) }}</small></div><div v-if="!(detail.usage.chart || []).length" class="empty compact-empty">暂无使用记录</div></div></div>
      <div class="panel account-control"><div class="panel-head"><div><span class="eyebrow">账户管理</span><h2>账户操作</h2></div><span :class="['account-state', detail.user.enabled ? 'is-on' : 'is-off']"><i></i>{{ detail.user.enabled ? '正常使用' : '已停用' }}</span></div><div class="account-status-line"><span>账户余额</span><strong>¥{{ money(detail.user.balance) }}</strong></div><label>设置余额<input v-model.number="balanceForm.balance" type="number" min="-0.1" step="0.0001" /></label><label>重置密码<input v-model="passwordForm.password" type="password" minlength="6" maxlength="128" placeholder="输入新密码" /></label><div class="account-actions"><button class="primary-btn full" :disabled="saving" @click="saveBalance">{{ saving ? '保存中…' : '保存余额' }}</button><button class="secondary-btn full" :disabled="passwordSaving || !passwordForm.password" @click="savePassword">{{ passwordSaving ? '保存中…' : '保存密码' }}</button><button class="secondary-btn full" @click="toggleUser">{{ detail.user.enabled ? '禁用账户' : '启用账户' }}</button><button class="danger-btn full" @click="deleteAccount">删除账户</button></div><p class="muted">余额最低允许 -0.1 元；余额低于 0.001 元时不能继续调用模型。</p></div>
    </div>

    <div v-if="detail.user" class="panel entitlement-admin-panel">
      <div class="panel-head"><div><span class="eyebrow">FREE QUOTA POLICY</span><h2>用户免费赠送额度</h2><p class="panel-note">这是赠送给用户的免费调用权益，不是额外扣费项。正数表示该项的免费上限；0 只表示该项不限，三项全为 0 才是有效期内不限量免费。用量顺序为：免费额度 → 套餐 → 钱包。</p></div></div>
      <form class="quota-form" @submit.prevent="saveQuota"><input v-model.trim="quotaForm.name" placeholder="免费额度名称" required /><label>每日免费金额上限<input v-model.number="quotaForm.daily_amount" type="number" min="0" step="0.0001" /></label><label>每日免费 Token 上限<input v-model.number="quotaForm.daily_tokens" type="number" min="0" step="1" /></label><label>滚动窗口 Token 上限<input v-model.number="quotaForm.hourly_tokens" type="number" min="0" step="1" /></label><label>滚动窗口小时<input v-model.number="quotaForm.hourly_window_hours" type="number" min="0.1" max="168" step="0.1" /></label><label>开始日期<input v-model="quotaForm.starts_at" type="datetime-local" /></label><label>结束日期<input v-model="quotaForm.ends_at" type="datetime-local" /></label><label class="quota-enabled">启用<input v-model="quotaForm.enabled" type="checkbox" /></label><button class="primary-btn" :disabled="quotaSaving">{{ quotaSaving ? '保存中…' : editingQuota ? '保存额度' : '赠送免费额度' }}</button><button v-if="editingQuota" type="button" class="secondary-btn" @click="resetQuotaForm">取消编辑</button></form>
      <div v-if="detail.quotas.length" class="quota-list"><article v-for="item in detail.quotas" :key="item.id" :class="['admin-quota-card', 'quota-tone-' + (item.id % 3)]"><div class="admin-quota-top"><div><span class="plan-id">FREE GRANT</span><h3>{{ item.name }}</h3></div><span :class="['status', item.enabled ? 'success' : 'pending']">{{ item.enabled ? '赠送中' : '已停用' }}</span></div><div class="admin-quota-period">{{ item.starts_at ? format(item.starts_at) : '-' }} <b>→</b> {{ item.ends_at ? format(item.ends_at) : '长期有效' }}</div><div class="admin-quota-specs"><div><small>每日免费金额上限</small><b>{{ item.daily_amount > 0 ? `¥${Number(item.daily_amount).toFixed(4)}` : '该项不限' }}</b></div><div><small>每日免费 Token 上限</small><b>{{ item.daily_tokens > 0 ? Number(item.daily_tokens).toLocaleString('zh-CN') : '该项不限' }}</b></div><div><small>滚动窗口 Token 上限</small><b>{{ item.hourly_tokens > 0 ? Number(item.hourly_tokens).toLocaleString('zh-CN') + ' / ' + item.hourly_window_hours + ' 小时' : '该项不限' }}</b></div></div><div class="admin-quota-actions"><button class="secondary-btn" @click="editQuota(item)">编辑</button><button class="text-btn danger" @click="removeQuota(item)">删除</button></div></article></div><div v-else class="empty compact-empty">尚未赠送免费额度</div>
      <div v-if="detail.quotas_pagination.pages > 1" class="pagination"><button class="secondary-btn" :disabled="detail.quotas_pagination.page <= 1" @click="changeQuotaPage(detail.quotas_pagination.page - 1)">上一页</button><span>第 {{ detail.quotas_pagination.page }} / {{ detail.quotas_pagination.pages }} 页，共 {{ detail.quotas_pagination.total }} 条</span><button class="secondary-btn" :disabled="detail.quotas_pagination.page >= detail.quotas_pagination.pages" @click="changeQuotaPage(detail.quotas_pagination.page + 1)">下一页</button></div>
    </div>

    <div v-if="detail.user" class="admin-user-bottom-grid">
    <div class="panel admin-user-subscriptions">
      <div class="panel-head"><div><span class="eyebrow">USER SUBSCRIPTIONS</span><h2>用户套餐</h2><p class="panel-note">管理员可以修改有效期、自动续订状态，也可以停用或删除套餐权益。</p></div></div>
      <div v-if="detail.subscriptions.length" class="admin-subscription-grid"><article v-for="item in detail.subscriptions" :key="item.id" class="admin-subscription-card"><div class="admin-subscription-top"><div><span class="plan-id">PLAN {{ String(item.plan_id).padStart(2, '0') }}</span><h3>{{ item.plan_name }}</h3></div><span :class="['status', item.status === 'ACTIVE' ? 'success' : 'pending']">{{ subscriptionStatus(item.status) }}</span></div><div class="admin-subscription-period">{{ format(item.starts_at) }} <b>→</b> {{ format(item.ends_at) }}</div><div class="admin-subscription-specs"><div><small>套餐价格</small><b>¥{{ Number(item.price || 0).toFixed(2) }}</b></div><div><small>每日额度</small><b>{{ item.daily_tokens > 0 ? Number(item.daily_tokens).toLocaleString('zh-CN') + ' Token' : '不限' }}</b></div><div><small>自动续订</small><b>{{ item.auto_renew ? '已开启' : '未开启' }}</b></div></div><div class="admin-subscription-actions"><button class="secondary-btn" @click="editSubscription(item)">编辑</button><button class="secondary-btn" @click="toggleSubscription(item)">{{ item.status === 'ACTIVE' ? '停用' : '启用' }}</button><button class="text-btn danger" @click="removeSubscription(item)">删除</button></div></article></div><div v-else class="empty compact-empty">暂无套餐订阅</div>
      <div v-if="editingSubscription" class="subscription-editor"><div class="subscription-editor-head"><div><span class="eyebrow">EDIT SUBSCRIPTION</span><strong>{{ editingSubscription.plan_name }}</strong></div><button class="icon-btn" type="button" @click="resetSubscriptionForm">×</button></div><form class="subscription-editor-form" @submit.prevent="saveSubscription"><label>开始时间<input v-model="subscriptionForm.starts_at" type="datetime-local" required /></label><label>结束时间<input v-model="subscriptionForm.ends_at" type="datetime-local" required /></label><label>状态<select v-model="subscriptionForm.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option><option value="EXPIRED">已过期</option><option value="CANCELLED">已取消</option></select></label><label class="subscription-auto-renew">自动续订<input v-model="subscriptionForm.auto_renew" type="checkbox" /></label><div class="subscription-editor-actions"><button class="secondary-btn" type="button" @click="resetSubscriptionForm">取消</button><button class="primary-btn" :disabled="subscriptionSaving" type="submit">{{ subscriptionSaving ? '保存中…' : '保存套餐' }}</button></div></form></div>
      <div v-if="detail.subscriptions_pagination.pages > 1" class="pagination"><button class="secondary-btn" :disabled="detail.subscriptions_pagination.page <= 1" @click="changeSubscriptionPage(detail.subscriptions_pagination.page - 1)">上一页</button><span>第 {{ detail.subscriptions_pagination.page }} / {{ detail.subscriptions_pagination.pages }} 页，共 {{ detail.subscriptions_pagination.total }} 条</span><button class="secondary-btn" :disabled="detail.subscriptions_pagination.page >= detail.subscriptions_pagination.pages" @click="changeSubscriptionPage(detail.subscriptions_pagination.page + 1)">下一页</button></div>
    </div>

    <div v-if="detail.user" class="panel admin-payment-history"><div class="panel-head"><div><span class="eyebrow">PAYMENT HISTORY</span><h2>充值与兑换记录</h2></div></div><div class="table-wrap"><table><thead><tr><th>订单号</th><th>来源</th><th>金额</th><th>状态</th><th>时间</th></tr></thead><tbody><tr v-for="item in detail.orders" :key="item.id"><td><code>{{ item.trade_no }}</code></td><td>{{ labels[item.provider] || item.provider }}</td><td>¥{{ Number(item.amount || 0).toFixed(2) }}</td><td>{{ item.status }}</td><td>{{ format(item.created_at) }}</td></tr></tbody></table></div><div v-if="!detail.orders.length" class="empty compact-empty">暂无充值或兑换记录</div><div class="pagination" v-if="detail.orders_pagination.pages > 1"><button class="secondary-btn" :disabled="detail.orders_pagination.page <= 1" @click="changeOrderPage(detail.orders_pagination.page - 1)">上一页</button><span>第 {{ detail.orders_pagination.page }} / {{ detail.orders_pagination.pages }} 页，共 {{ detail.orders_pagination.total }} 条</span><button class="secondary-btn" :disabled="detail.orders_pagination.page >= detail.orders_pagination.pages" @click="changeOrderPage(detail.orders_pagination.page + 1)">下一页</button></div></div>
    </div>
  </section>
</template>

<script>
import { api } from '../api'
import { notify, askConfirm } from '../ui'

const emptyQuota = () => ({ name: '', daily_amount: 0, daily_tokens: 0, hourly_tokens: 0, hourly_window_hours: 1, starts_at: '', ends_at: '', enabled: true })
const emptySubscription = () => ({ starts_at: '', ends_at: '', status: 'ACTIVE', auto_renew: false })

export default {
  props: { id: [String, Number] },
  data: () => ({
    detail: { usage: { chart: [] }, orders_pagination: { page: 1, pages: 1, total: 0 }, quotas_pagination: { page: 1, pages: 1, total: 0 }, subscriptions_pagination: { page: 1, pages: 1, total: 0 }, subscriptions: [], quotas: [] },
    ranges: [{ key: 'today', label: '今日' }, { key: 'week', label: '本周' }, { key: 'month', label: '本月' }, { key: 'total', label: '历史' }],
    balanceForm: { balance: 0 }, passwordForm: { password: '' }, quotaForm: emptyQuota(), subscriptionForm: emptySubscription(), editingQuota: null, editingSubscription: null, quotaSaving: false, subscriptionSaving: false, saving: false, passwordSaving: false,
    labels: { WECHAT_PERSONAL: '微信支付', WECHAT: '微信支付', ALIPAY: '支付宝', CODE: '兑换码', SUBSCRIPTION: '套餐续订' }
  }),
  created () { this.load() },
  methods: {
    async load () { try { const d = await api.userDetail(this.id, { page: this.detail.orders_pagination.page, page_size: 5 }); if (!d.ok) throw new Error(d.message); this.detail = { ...this.detail, ...d, usage: d.usage || { chart: [] }, subscriptions: d.subscriptions || [], quotas: d.quotas || [], subscriptions_pagination: d.subscriptions_pagination || this.detail.subscriptions_pagination }; this.balanceForm.balance = Number(d.user.balance || 0); this.passwordForm.password = '' } catch (e) { notify(e.message, 'error') } },
    money (n) { return Number(n || 0).toFixed(4) }, compact (n) { n = Number(n || 0); return n > 999999 ? `${(n / 1000000).toFixed(2)}M` : n > 999 ? `${(n / 1000).toFixed(1)}K` : n },
    barHeight (n) { const values = (this.detail.usage.chart || []).map(i => Number(i.tokens || 0)); const max = Math.max(...values, 1); return `${Math.max(8, Number(n || 0) / max * 100)}%` },
    format (s) { return s ? new Date(s).toLocaleString('zh-CN') : '-' }, localInput (s) { return s ? new Date(s).toISOString().slice(0, 16) : '' }, isoInput (s) { return s ? new Date(s).toISOString() : null },
    subscriptionStatus (status) { return { ACTIVE: '启用', DISABLED: '停用', EXPIRED: '已过期', CANCELLED: '已取消' }[status] || status || '-' },
    resetQuotaForm () { this.editingQuota = null; this.quotaForm = emptyQuota() },
    editQuota (item) { this.editingQuota = item; this.quotaForm = { name: item.name, daily_amount: Number(item.daily_amount || 0), daily_tokens: Number(item.daily_tokens || 0), hourly_tokens: Number(item.hourly_tokens || 0), hourly_window_hours: Number(item.hourly_window_hours || 1), starts_at: this.localInput(item.starts_at), ends_at: this.localInput(item.ends_at), enabled: !!item.enabled } },
    async saveQuota () { this.quotaSaving = true; try { const body = { ...this.quotaForm, starts_at: this.isoInput(this.quotaForm.starts_at), ends_at: this.isoInput(this.quotaForm.ends_at) }; const d = this.editingQuota ? await api.updateUserQuota(this.id, this.editingQuota.id, body) : await api.createUserQuota(this.id, body); if (!d.ok) throw new Error(d.message); notify(this.editingQuota ? '免费额度已更新' : '免费额度已创建', 'success'); this.resetQuotaForm(); await this.load() } catch (e) { notify(e.message, 'error') } finally { this.quotaSaving = false } },
    async removeQuota (item) { if (!await askConfirm(`确定删除额度「${item.name}」吗？`)) return; try { const d = await api.deleteUserQuota(this.id, item.id); if (!d.ok) throw new Error(d.message); await this.load(); notify('免费额度已删除', 'success') } catch (e) { notify(e.message, 'error') } },
    async changeQuotaPage (page) { try { const d = await api.userQuotas(this.id, { page, page_size: 5 }); if (!d.ok) throw new Error(d.message); this.$set(this.detail, 'quotas', d.quotas || []); this.$set(this.detail, 'quotas_pagination', d.pagination || this.detail.quotas_pagination) } catch (e) { notify(e.message, 'error') } },
    editSubscription (item) { this.editingSubscription = item; this.subscriptionForm = { starts_at: this.localInput(item.starts_at), ends_at: this.localInput(item.ends_at), status: item.status || 'ACTIVE', auto_renew: !!item.auto_renew } },
    resetSubscriptionForm () { this.editingSubscription = null; this.subscriptionForm = emptySubscription() },
    async saveSubscription () { if (!this.editingSubscription) return; this.subscriptionSaving = true; try { const body = { ...this.subscriptionForm, starts_at: this.isoInput(this.subscriptionForm.starts_at), ends_at: this.isoInput(this.subscriptionForm.ends_at) }; const d = await api.updateUserSubscription(this.id, this.editingSubscription.id, body); if (!d.ok) throw new Error(d.message); notify('用户套餐已更新', 'success'); this.resetSubscriptionForm(); await this.load() } catch (e) { notify(e.message, 'error') } finally { this.subscriptionSaving = false } },
    async toggleSubscription (item) { const next = item.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'; if (!await askConfirm(`${next === 'ACTIVE' ? '启用' : '停用'}套餐「${item.plan_name}」吗？`)) return; try { const d = await api.updateUserSubscription(this.id, item.id, { status: next, auto_renew: next === 'ACTIVE' && !!item.auto_renew }); if (!d.ok) throw new Error(d.message); await this.load(); notify(next === 'ACTIVE' ? '用户套餐已启用' : '用户套餐已停用', 'success') } catch (e) { notify(e.message, 'error') } },
    async removeSubscription (item) { if (!await askConfirm(`删除用户套餐「${item.plan_name}」后，该权益记录将永久移除，确定继续吗？`)) return; try { const d = await api.deleteUserSubscription(this.id, item.id); if (!d.ok) throw new Error(d.message); if (this.editingSubscription?.id === item.id) this.resetSubscriptionForm(); await this.load(); notify('用户套餐已删除', 'success') } catch (e) { notify(e.message, 'error') } },
    async changeSubscriptionPage (page) { try { const d = await api.userSubscriptions(this.id, { page, page_size: 5 }); if (!d.ok) throw new Error(d.message); this.$set(this.detail, 'subscriptions', d.subscriptions || []); this.$set(this.detail, 'subscriptions_pagination', d.pagination || this.detail.subscriptions_pagination) } catch (e) { notify(e.message, 'error') } },
    changeOrderPage (page) { this.detail.orders_pagination.page = page; this.load() },
    async saveBalance () { this.saving = true; try { const d = await api.updateUser(this.id, { balance: Math.max(-0.1, Number(this.balanceForm.balance || 0)) }); if (!d.ok) throw new Error(d.message); await this.load(); notify('余额已保存', 'success') } catch (e) { notify(e.message, 'error') } finally { this.saving = false } },
    async savePassword () { this.passwordSaving = true; try { const password = String(this.passwordForm.password || ''); if (password.length < 6) throw new Error('密码长度需为 6-128 位'); const d = await api.updateUser(this.id, { password }); if (!d.ok) throw new Error(d.message); await this.load(); notify('密码已更新', 'success') } catch (e) { notify(e.message, 'error') } finally { this.passwordSaving = false } },
    async toggleUser () { try { const d = await api.updateUser(this.id, { enabled: !this.detail.user.enabled }); if (!d.ok) throw new Error(d.message); await this.load(); notify('账户状态已更新', 'success') } catch (e) { notify(e.message, 'error') } },
    async deleteAccount () { if (!await askConfirm('删除账户后，该用户的密钥、用量和订单记录都会删除，确定继续吗？')) return; try { const d = await api.deleteUser(this.id); if (!d.ok) throw new Error(d.message); notify('账户已删除', 'success'); this.$router.push('/admin') } catch (e) { notify(e.message, 'error') } }
  }
}
</script>
