<template>
  <section class="page"><div class="page-head"><div><div class="eyebrow">OVERVIEW / {{ today }}</div><h1>控制台</h1><p>你的 API 流量、余额和接入信息。</p></div><router-link class="primary-btn" to="/models">开始调用 →</router-link></div><div class="metric-grid"><div class="metric-card highlight"><span>当前余额</span><strong>¥{{ money(userInfo.balance) }}</strong><router-link to="/billing">充值余额 →</router-link></div><div class="metric-card"><span>累计请求</span><strong>{{ usage.requests || 0 }}</strong><small>成功完成的请求</small><b class="metric-tag">+{{ usage.requests ? '100%' : '0%' }} / 本月</b></div><div class="metric-card"><span>消耗 Token</span><strong>{{ compact(usage.total_tokens) }}</strong><small>输入 + 输出</small><b class="metric-tag">按实际用量</b></div><div class="metric-card"><span>累计消费</span><strong>¥{{ money(usage.total_cost) }}</strong><small>已结算金额</small><b class="metric-tag">按用量结算</b></div></div><div class="dashboard-columns"><div class="panel usage-panel"><div class="panel-head"><div><span class="eyebrow">RECENT ACTIVITY</span><h2>最近用量</h2></div><router-link to="/docs">API 文档 ↗</router-link></div><div v-if="usage.recent && usage.recent.length" class="table-wrap"><table><thead><tr><th>时间</th><th>模型</th><th>Tokens</th><th>费用</th><th>状态</th></tr></thead><tbody><tr v-for="row in usage.recent" :key="row.id"><td>{{ formatDate(row.created_at) }}</td><td><span class="model-pill">{{ row.model }}</span></td><td>{{ row.total_tokens }}</td><td>¥{{ money(row.cost) }}</td><td><span class="status success">已完成</span></td></tr></tbody></table></div><div v-else class="empty"><div class="empty-icon">◌</div><strong>还没有调用记录</strong><p>用你的 API Key 发起第一次请求。</p><router-link to="/docs">查看接入示例 →</router-link></div><div class="pagination" v-if="usage.recent_pagination && usage.recent_pagination.pages > 1"><button class="secondary-btn" :disabled="usage.recent_pagination.page <= 1" @click="changeUsagePage(usage.recent_pagination.page - 1)">上一页</button><span>第 {{ usage.recent_pagination.page }} / {{ usage.recent_pagination.pages }} 页，共 {{ usage.recent_pagination.total }} 条</span><button class="secondary-btn" :disabled="usage.recent_pagination.page >= usage.recent_pagination.pages" @click="changeUsagePage(usage.recent_pagination.page + 1)">下一页</button></div></div><div class="panel api-panel"><div class="panel-head"><div><span class="eyebrow">QUICK CONNECT</span><h2>API Key</h2></div><router-link class="secondary-btn" to="/keys">管理密钥</router-link></div><p class="panel-note">API 密钥需要在密钥页面主动创建，删除后立即停止调用。</p><div class="endpoint"><span>BASE URL</span><code>{{ baseUrl }}/v1</code></div><div class="api-tip"><span class="tip-mark">i</span><span>费用按实际用量结算，结果中会返回本次费用。</span></div></div></div></section>
</template>
<script>
import { api } from '../api'
export default { props: { user: Object, apiBaseUrl: String }, data () { return { userInfo: {}, usage: {}, today: '', baseUrl: this.apiBaseUrl || '', usagePage: 1 } }, watch: { apiBaseUrl (value) { if (value) this.baseUrl = value.replace(/\/$/, '') } }, created () { this.today = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' }); this.load() }, methods: { async load () { try { const d = await api.dashboard({ page: this.usagePage, page_size: 5 }); this.userInfo = d.user || {}; this.usage = d.usage || {} } catch (e) {} }, changeUsagePage (page) { this.usagePage = page; this.load() }, money (n) { return Number(n || 0).toFixed(4) }, compact (n) { n = Number(n || 0); return n > 999999 ? (n / 1000000).toFixed(2) + 'M' : n > 999 ? (n / 1000).toFixed(1) + 'K' : n }, formatDate (s) { return s ? new Date(s).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '-' } } }
</script>


