<template>
  <section class="page">
    <div class="page-head"><div><div class="eyebrow">ACCESS / CREDENTIALS</div><h1>API 密钥</h1><p>为不同应用创建独立密钥，删除后立即停止调用。</p></div><button class="primary-btn" :disabled="loading" @click="openCreate">＋ 新建密钥</button></div>
    <div class="panel key-summary"><div><span class="eyebrow">ENDPOINT</span><h2>{{ baseUrl }}/v1</h2></div><div><span class="eyebrow">活跃密钥</span><strong>{{ activeCount }}</strong></div><router-link class="secondary-btn" to="/docs">查看配置教程 ↗</router-link></div>
    <div class="panel keys-panel"><div class="panel-head"><div><span class="eyebrow">KEY DIRECTORY</span><h2>密钥列表</h2></div><button class="icon-btn keys-refresh" :class="{ spinning: refreshing }" :disabled="refreshing" title="刷新" @click.prevent="load">↻</button></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>API 密钥</th><th>状态</th><th>创建时间</th><th>最近使用</th><th>操作</th></tr></thead><tbody><tr v-for="item in keys" :key="item.id"><td><strong>{{ item.name }}</strong><small v-if="item.id === freshKeyId" class="fresh-key-label">刚刚创建</small></td><td><code>{{ item.id === freshKeyId ? item.api_key : masked(item.api_key) }}</code><button class="copy-btn" @click="copy(item.api_key)">复制</button></td><td><span :class="['status', item.enabled ? 'success' : 'pending']">{{ item.enabled ? '已启用' : '已撤销' }}</span></td><td>{{ format(item.created_at) }}</td><td>{{ item.last_used ? format(item.last_used) : '暂无使用' }}</td><td><button class="text-btn danger" @click="remove(item)">删除</button></td></tr></tbody></table></div><div v-if="!keys.length" class="empty compact-empty">暂无 API 密钥，请点击右上角新建。</div><div class="pagination" v-if="pagination.pages > 1"><button class="secondary-btn" :disabled="pagination.page <= 1" @click="changePage(pagination.page - 1)">上一页</button><span>第 {{ pagination.page }} / {{ pagination.pages }} 页，共 {{ pagination.total }} 条</span><button class="secondary-btn" :disabled="pagination.page >= pagination.pages" @click="changePage(pagination.page + 1)">下一页</button></div></div>
    <div v-if="createOpen" class="modal-backdrop"><div class="modal-card"><button class="modal-close" aria-label="关闭" @click="createOpen = false">×</button><span class="eyebrow">NEW CREDENTIAL</span><h2>新建 API 密钥</h2><p class="panel-note">请为这个密钥设置一个便于识别的名称。</p><label>密钥名称<input v-model.trim="createName" maxlength="64" autofocus placeholder="例如：生产环境 / Cursor" @keyup.enter="quickCreate" /></label><p v-if="createError" class="form-error">{{ createError }}</p><div class="feedback-actions"><button class="secondary-btn" @click="createOpen = false">取消</button><button class="primary-btn" :disabled="loading || !createName" @click="quickCreate">{{ loading ? '创建中…' : '创建密钥' }}</button></div></div></div>
  </section>
</template>
<script>
import { api } from '../api'
import { copyToClipboard, notify, askConfirm } from '../ui'
export default { props: { apiBaseUrl: String }, data () { return { keys: [], pagination: { page: 1, pages: 1, total: 0 }, loading: false, refreshing: false, freshKeyId: null, baseUrl: this.apiBaseUrl || '', createOpen: false, createName: '', createError: '' } }, computed: { activeCount () { return this.keys.filter(item => item.enabled).length } }, watch: { apiBaseUrl (value) { if (value) this.baseUrl = value.replace(/\/$/, '') } }, created () { this.load(false) }, methods: { async load (preservePosition = true) { if (this.refreshing) return; const scrollX = window.scrollX; const scrollY = window.scrollY; this.refreshing = true; try { const d = await api.keys({ page: this.pagination.page, page_size: 5 }); this.keys = d.keys || []; this.pagination = d.pagination || this.pagination; this.freshKeyId = null } catch (e) { notify(e.message, 'error') } finally { this.refreshing = false; if (preservePosition) this.$nextTick(() => window.scrollTo(scrollX, scrollY)) } }, changePage (page) { this.pagination.page = page; this.load(true) }, openCreate () { this.createName = ''; this.createError = ''; this.createOpen = true }, async quickCreate () { if (!this.createName) { this.createError = '请输入密钥名称'; return }; const scrollX = window.scrollX; const scrollY = window.scrollY; this.loading = true; try { const d = await api.createKey({ name: this.createName }); if (!d.ok || !d.key) throw new Error(d.message || '创建密钥失败'); this.createOpen = false; this.freshKeyId = d.key.id; this.pagination.page = 1; this.pagination.total = Number(this.pagination.total || 0) + 1; this.pagination.pages = Math.max(1, Math.ceil(this.pagination.total / 5)); this.keys = [d.key, ...this.keys.filter(item => item.id !== d.key.id)].slice(0, 5); this.$nextTick(() => window.scrollTo(scrollX, scrollY)); notify('密钥已创建，已添加到列表顶部', 'success') } catch (e) { this.createError = e.message; notify(e.message, 'error') } finally { this.loading = false } }, async remove (item) { if (!await askConfirm(`确定删除“${item.name}”吗？`)) return; try { const d = await api.deleteKey(item.id); if (!d.ok) throw new Error(d.message); this.keys = this.keys.filter(row => row.id !== item.id); this.pagination.total = Math.max(0, Number(this.pagination.total || 0) - 1); this.pagination.pages = Math.max(1, Math.ceil(this.pagination.total / 5)); if (!this.keys.length && this.pagination.page > 1) this.pagination.page -= 1; notify('密钥已删除', 'success') } catch (e) { notify(e.message, 'error') } }, masked (value) { return value ? `${value.slice(0, 12)}${'•'.repeat(12)}${value.slice(-4)}` : '-' }, async copy (value) { const copied = await copyToClipboard(value); notify(copied ? '已复制' : '复制失败，请检查浏览器权限', copied ? 'success' : 'error') }, format (value) { return value ? new Date(value).toLocaleString('zh-CN') : '-' } } }
</script>

