<template>
  <section class="page monitoring-page"><div class="page-head"><div><div class="eyebrow">OBSERVABILITY / MODEL HEALTH</div><h1>模型监控</h1><p>统一查看配置模型、订阅账号池模型与最近 24 小时调用量。</p></div><button class="secondary-btn" @click="load">刷新数据 ↻</button></div><div class="metric-grid"><div class="metric-card highlight"><span>可用模型</span><strong>{{ summary.available || 0 }}/{{ summary.total || 0 }}</strong><small>包含 YAML 配置与订阅网关模型</small></div><div class="metric-card"><span>24H 请求</span><strong>{{ totalRequests }}</strong><small>按当前账户统计</small></div><div class="metric-card"><span>24H Token</span><strong>{{ compact(totalTokens) }}</strong><small>输入 + 输出</small></div><div class="metric-card"><span>更新时间</span><strong>{{ updated ? '刚刚' : '-' }}</strong><small>{{ updated ? format(updated) : '暂无数据' }}</small></div></div><div class="monitor-grid"><article v-for="model in models" :key="model.id" class="monitor-card"><div class="monitor-head"><div><span class="model-letter">{{ (model.provider || model.id).slice(0, 1).toUpperCase() }}</span><strong>{{ model.id }}</strong></div><span :class="['availability', model.status === '正常' ? '' : 'offline']"><i></i>{{ model.status }}</span></div><div class="health-bars"><span v-for="n in 12" :key="n" :class="n <= (model.status === '正常' ? 12 : 2) ? 'ok' : 'idle'"></span></div><p class="muted">{{ model.health?.detail || '暂无检测信息' }}<span v-if="model.health?.latency_ms"> · {{ model.health.latency_ms }} ms</span></p><div class="monitor-stats"><span><small>24H 请求</small><b>{{ model.requests_24h }}</b></span><span><small>24H Token</small><b>{{ compact(model.tokens_24h) }}</b></span><span><small>24H 消费</small><b>¥{{ Number(model.cost_24h || 0).toFixed(4) }}</b></span></div><div class="monitor-foot"><span>{{ model.provider }} · {{ model.group }}</span><router-link to="/docs">调用示例 ↗</router-link></div></article></div><div v-if="!models.length" class="empty">暂无监控数据</div><div class="pagination" v-if="pagination.pages > 1"><button class="secondary-btn" :disabled="pagination.page <= 1" @click="changePage(pagination.page - 1)">上一页</button><span>第 {{ pagination.page }} / {{ pagination.pages }} 页，共 {{ pagination.total }} 个模型</span><button class="secondary-btn" :disabled="pagination.page >= pagination.pages" @click="changePage(pagination.page + 1)">下一页</button></div></section>
</template>
<script>
import { api } from '../api'
import { notify } from '../ui'
export default { data: () => ({ models: [], summary: {}, updated: '', pagination: { page: 1, pages: 1, total: 0 } }), computed: { totalRequests () { return this.models.reduce((sum, item) => sum + Number(item.requests_24h || 0), 0) }, totalTokens () { return this.models.reduce((sum, item) => sum + Number(item.tokens_24h || 0), 0) } }, created () { this.load() }, methods: { async load () { try { const d = await api.monitoring({ page: this.pagination.page, page_size: 12 }); this.models = d.models || []; this.summary = d.summary || {}; this.updated = d.updated_at || ''; this.pagination = d.pagination || this.pagination } catch (e) { notify(e.message, 'error') } }, changePage (page) { this.pagination.page = page; this.load() }, compact (value) { const n = Number(value || 0); return n > 1000000 ? `${(n / 1000000).toFixed(2)}M` : n > 1000 ? `${(n / 1000).toFixed(1)}K` : n }, format (value) { return value ? new Date(value).toLocaleString('zh-CN') : '-' } } }
</script>

